version: "3"

services:
  astrocouch:
    image: zachlankton/astrocouch
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: service:couchdb
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
      - COUCHDB_SECRET=superSensitiveSecret
      - NODENAME=node
      - ERL_FLAGS=-setcookie "brumbrum"
