name: All Tests and Coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # use localhost for the host here because we are running the job on the VM.
      # If we were running the job on in a container this would be postgres
      LOGLEVEL: INFO
      DB_SSL: false
      DB_DOMAIN: localhost
      DB_PORT: 5984
      DB_NAME: test
      DB_PASS: admin
      DB_USER: admin

    services:
      couchdb:
        image: couchdb:3.2
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: admin
          COUCHDB_SECRET: superSensitiveSecret
          NODENAME: node
          ERL_FLAGS: -setcookie "brumbrum"
        ports:
          # will assign a random free host port
          - 5984:5984
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd "curl http://localhost:5984" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Seed Database
        run: ./.devcontainer/seed_db.sh
      - name: Run All Tests and Coverage
        run: npm run test:coverage
      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
